# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c
sudo: required
dist: trusty
group: edge

env:
  global:
    - RunAllRcppAnnoyTests="yes"
  matrix:
    - R_VERSION="3.4"
    - R_VERSION="3.5"

before_install:
  #- curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - curl -OLs http://dirk.eddelbuettel.com/tmp/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-runit r-cran-rcpp

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
